
NEAR_DUPLICATE_COSINE_THRESHOLD = 0.97
SCORE_THRESHOLD = 0.65
MARGIN_THRESHOLD = 0.03
MAX_TOP_K = 5
MAX_CONTEXT_CHARS = 6000
MAX_CHUNK_SNIPPET_CHARS = 800
SOURCE_SNIPPET_CHARS = 300
MODEL_NAME = "mistralai/Mistral-7B-Instruct-v0.2"
